<?php

return [
    ['value' => 'abap', 'label' => 'Abap'],
    ['value' => 'aes', 'label' => 'Aes'],
    ['value' => 'apex', 'label' => 'Apex'],
    ['value' => 'azcli', 'label' => 'Azure CLI'],
    ['value' => 'bat', 'label' => 'BAT'],
    ['value' => 'bicep', 'label' => 'Bicep'],
    ['value' => 'c', 'label' => 'C'],
    ['value' => 'cameligo', 'label' => 'Cameligo'],
    ['value' => 'clojure', 'label' => 'Clojure'],
    ['value' => 'coffeescript', 'label' => 'CoffeeScript'],
    ['value' => 'cpp', 'label' => 'C++'],
    ['value' => 'csharp', 'label' => 'C#'],
    ['value' => 'csp', 'label' => 'CSP'],
    ['value' => 'css', 'label' => 'CSS'],
    ['value' => 'cypher', 'label' => 'Cypher'],
    ['value' => 'dart', 'label' => 'Dart'],
    ['value' => 'dockerfile', 'label' => 'Dockerfile'],
    ['value' => 'ecl', 'label' => 'ECL'],
    ['value' => 'elixir', 'label' => 'Elixir'],
    ['value' => 'flow9', 'label' => 'Flow9'],
    ['value' => 'freemarker2', 'label' => 'Freemarker2'],
    ['value' => 'fsharp', 'label' => 'F#'],
    ['value' => 'go', 'label' => 'Go'],
    ['value' => 'graphql', 'label' => 'GraphQL'],
    ['value' => 'handlebars', 'label' => 'Handlebars'],
    ['value' => 'hcl', 'label' => 'HCL'],
    ['value' => 'html', 'label' => 'HTML'],
    ['value' => 'ini', 'label' => 'INI'],
    ['value' => 'java', 'label' => 'Java'],
    ['value' => 'javascript', 'label' => 'JavaScript'],
    ['value' => 'json', 'label' => 'JSON'],
    ['value' => 'julia', 'label' => 'Julia'],
    ['value' => 'kotlin', 'label' => 'Kotlin'],
    ['value' => 'less', 'label' => 'Less'],
    ['value' => 'lexon', 'label' => 'Lexon'],
    ['value' => 'liquid', 'label' => 'Liquid'],
    ['value' => 'lua', 'label' => 'Lua'],
    ['value' => 'm3', 'label' => 'M3'],
    ['value' => 'markdown', 'label' => 'Markdown'],
    ['value' => 'mips', 'label' => 'Mips'],
    ['value' => 'msdax', 'label' => 'MsDax'],
    ['value' => 'mysql', 'label' => 'MySQL'],
    ['value' => 'objective-c', 'label' => 'Objective-C'],
    ['value' => 'pascal', 'label' => 'Pascal'],
    ['value' => 'pascaligo', 'label' => 'Pascaligo'],
    ['value' => 'perl', 'label' => 'Perl'],
    ['value' => 'pgsql', 'label' => 'PgSQL'],
    ['value' => 'php', 'label' => 'PHP'],
    ['value' => 'pla', 'label' => 'PLA'],
    ['value' => 'plaintext', 'label' => 'Plain Text'],
    ['value' => 'postiats', 'label' => 'Pstiats'],
    ['value' => 'powerquery', 'label' => 'PowerQuery'],
    ['value' => 'powershell', 'label' => 'PowerShell'],
    ['value' => 'proto', 'label' => 'Proto'],
    ['value' => 'pug', 'label' => 'Pug'],
    ['value' => 'python', 'label' => 'Python'],
    ['value' => 'qsharp', 'label' => 'Q#'],
    ['value' => 'r', 'label' => 'R'],
    ['value' => 'razor', 'label' => 'Razor'],
    ['value' => 'redis', 'label' => 'Redis'],
    ['value' => 'redshift', 'label' => 'Redshift'],
    ['value' => 'restructuredtext', 'label' => 'Restructured Text'],
    ['value' => 'ruby', 'label' => 'Ruby'],
    ['value' => 'rust', 'label' => 'Rust'],
    ['value' => 'sb', 'label' => 'SB'],
    ['value' => 'scala', 'label' => 'Scala'],
    ['value' => 'scheme', 'label' => 'Scheme'],
    ['value' => 'scss', 'label' => 'SCSS'],
    ['value' => 'shell', 'label' => 'Shell'],
    ['value' => 'sol', 'label' => 'Sol'],
    ['value' => 'sparql', 'label' => 'SparQL'],
    ['value' => 'sql', 'label' => 'SQL'],
    ['value' => 'st', 'label' => 'ST'],
    ['value' => 'swift', 'label' => 'Swift'],
    ['value' => 'systemverilog', 'label' => 'System Verilog'],
    ['value' => 'tcl', 'label' => 'TCL'],
    ['value' => 'twig', 'label' => 'Twig'],
    ['value' => 'typescript', 'label' => 'TypeScript'],
    ['value' => 'vb', 'label' => 'Visual Basic'],
    ['value' => 'verilog', 'label' => 'Verilog'],
    ['value' => 'xml', 'label' => 'XML'],
    ['value' => 'yaml', 'label' => 'YAML'],
];
