name: Code Analysis

on:
  pull_request: null
  push:
    branches:
      - develop-v5
permissions:
  contents: read
jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        actions:
          -
            name: 'PHPStan'
            run: composer phpstan

          -
            name: 'Composer Validate'
            run: composer validate

          -
            name: 'Coding Standards'
            run: composer fix-cs

    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
      # see https://github.com/shivammathur/setup-php
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            coverage: none

      # composer install cache - https://github.com/ramsey/composer-install
      -   uses: "ramsey/composer-install@v1"
      -   run: ${{ matrix.actions.run }}
